#
# Copyright 2017 Okta, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

security:
  oauth2:
    client:
      clientAuthenticationScheme: header
      access-token-uri: https://dev-123456.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-123456.oktapreview.com/oauth2/default/v1/authorize
#      client-id: id
#      client-secret: secret
      scope: profile email openid
    resource:
      user-info-uri: https://dev-123456.oktapreview.com/oauth2/default/v1/userinfo
      token-info-uri: https://dev-123456.oktapreview.com/oauth2/default/v1/introspect
      prefer-token-info: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG


